### ISSUE TITLE
login twitter

### ISSUE THREAD

**Issue by jhouedanou** [akendewa/civblogs#15]
Bonsoir, 
je viens d'installer l'application sur [un serveur](http://demos.houedanou.com/civblogs-master) mais lors de l'étape où on doit se connecter à twitter , j'obtiens ceci.
![capture](https://f.cloud.github.com/assets/1837389/2423418/30966e6e-ab99-11e3-9fb1-6afe4291fe15.PNG)
Serait il possible d'avoir un coup de pouce à ce niveau ?

**Comment by regisbamba** [comment]
As tu parametré ta twitter api key  ?

**Comment by jhouedanou** [comment]
...oups..j'ai mis les paramètres dans le mauvais ordre. Ca fonctionne maintenant merci

**Comment by regisbamba** [comment]
Cool :-)
