### ISSUE TITLE
Partage sur les réseaux sociaux

### ISSUE THREAD

**Issue by jpehouman** [akendewa/civblogs#4]
la possibilité de partager sur les réseaux sociaux, ce serait intéressant si on pouvait partager mais le lien partagé est un lien interne au site qui redirige vers le blog. ça peut permettre de choisir un titre lors du partage sur les réseaux sociaux ==> CIVBlogs Akendewa : Lire ......

**Comment by yojedesign** [comment]
Aussi il faudra que le code source soit disponible merci
